/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Frosted Magenta design tokens (from DESIGN.md)
        'surface':                  '#131316',
        'surface-dim':              '#131316',
        'surface-bright':           '#39393c',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low':    '#1b1b1e',
        'surface-container':        '#1f1f22',
        'surface-container-high':   '#2a2a2d',
        'surface-container-highest':'#353438',
        'surface-variant':          '#353438',
        'on-surface':               '#e4e1e6',
        'on-surface-variant':       '#e4bdc4',
        'outline':                  '#ab888e',
        'outline-variant':          '#5b3f45',
        'background':               '#131316',
        'on-background':            '#e4e1e6',
        'primary':                  '#ffb1c2',
        'primary-container':        '#ff4c87',
        'on-primary':               '#66002b',
        'on-primary-container':     '#590025',
        'primary-fixed':            '#ffd9e0',
        'inverse-primary':          '#bb0055',
        'secondary':                '#e0b6ff',
        'secondary-container':      '#6d11ad',
        'on-secondary':             '#4c007d',
        'on-secondary-container':   '#d7a4ff',
        'tertiary':                 '#ffb0cb',
        'tertiary-container':       '#ea609b',
        'surface-tint':             '#ffb1c2',
        // Custom tokens
        'glass-stroke': 'rgba(255, 255, 255, 0.12)',
        'glass-fill':   'rgba(255, 255, 255, 0.06)',
        'bg-deep':      '#0f0c29',
        'bg-midnight':  '#302b63',
      },
      fontFamily: {
        'display-logo': ['"Playfair Display"', 'serif'],
        'sans-headline': ['"Plus Jakarta Sans"', 'sans-serif'],
        'sans-body':     ['Inter', 'sans-serif'],
        'mono':          ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '24px',
        'container-max': '1200px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      backdropBlur: {
        'glass': '20px',
        'nav': '30px',
      },
    },
  },
  plugins: [],
}
